const KEY='HomeShareUltraV5';
const DEFAULT={residents:['محمد أشرف','أحمد','صلاح'],expenses:[],history:[],settings:{currency:'USD',settlementDay:1}};
let s=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(DEFAULT), tab='home';
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const money=n=>`${s.settings.currency==='USD'?'$':'£'}${Number(n||0).toFixed(2)}`;
const total=()=>s.expenses.reduce((a,e)=>a+Number(e.amount||0),0);
const share=()=>s.residents.length?total()/s.residents.length:0;
function balances(){return s.residents.map(name=>{let paid=s.expenses.filter(e=>e.payer===name).reduce((a,e)=>a+Number(e.amount),0);return{name,paid,balance:paid-share()}})}
function transfers(){let d=balances().filter(x=>x.balance<-.005).map(x=>({...x,amount:-x.balance})), c=balances().filter(x=>x.balance>.005).map(x=>({...x,amount:x.balance})), out=[];let i=0,j=0;while(i<d.length&&j<c.length){let a=Math.min(d[i].amount,c[j].amount);out.push({from:d[i].name,to:c[j].name,amount:a});d[i].amount-=a;c[j].amount-=a;if(d[i].amount<.005)i++;if(c[j].amount<.005)j++}return out}
function toast(x){let d=document.createElement('div');d.className='toast';d.textContent=x;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function render(){let b=balances();document.getElementById('app').innerHTML=`<div class="shell">
<div class="top"><div class="brand"><b>HomeShare</b><span class="muted">Ultra Premium • Local</span></div><span class="badge">${s.residents.length} residents</span></div>
<nav class="nav">${[['home','⌂ Home'],['expenses','▣ Expenses'],['residents','♙ Residents'],['settlement','⇄ Settlement'],['history','◷ History'],['settings','⚙ Settings']].map(([k,l])=>`<button class="${tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('')}</nav>
${tab==='home'?home(b):tab==='expenses'?expenses():tab==='residents'?residents():tab==='settlement'?settlement():tab==='history'?history():settings()}
</div>`;
document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});
bind();
}
function home(b){return `<div class="hero"><h1>Your apartment, balanced.</h1><span class="muted">Every bill tracked. Every settlement explained.</span><div class="metrics"><div class="card"><span class="muted">Total</span><div class="metric">${money(total())}</div></div><div class="card"><span class="muted">Equal share</span><div class="metric">${money(share())}</div></div><div class="card"><span class="muted">Bills</span><div class="metric">${s.expenses.length}</div></div></div></div>
<div class="section card"><h2>Add expense</h2><div class="form"><select id="payer" class="input"><option value="">Who paid this bill?</option>${s.residents.map(n=>`<option>${n}</option>`).join('')}</select><div class="row"><input id="amount" class="input" type="number" step=".01" placeholder="Amount"><input id="date" class="input" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="row"><input id="desc" class="input" placeholder="Description"><input id="cat" class="input" placeholder="Category"></div><button class="btn" id="add">Add expense</button></div></div>
<div class="section card"><h2>Balances</h2>${b.map(x=>`<div class="expense"><span>${x.name}<div class="muted">Paid ${money(x.paid)}</div></span><b class="${x.balance>=0?'positive':'negative'}">${x.balance>=0?'+':''}${money(x.balance)}</b></div>`).join('')}</div>`}
function expenses(){return `<div class="card"><h2>Current expenses</h2>${s.expenses.length?s.expenses.slice().reverse().map(e=>`<div class="expense"><div><b>${e.description||'Expense'}</b><div class="muted">${e.payer} • ${e.category||'Other'} • ${e.date}</div></div><div class="actions"><b class="amount">${money(e.amount)}</b><button class="iconbtn" data-edit="${e.id}">Edit</button><button class="iconbtn" data-del="${e.id}">Delete</button></div></div>`).join(''):`<div class="empty">No expenses yet.</div>`}</div>`}
function residents(){return `<div class="card"><h2>Residents</h2><div class="row"><input id="newResident" class="input" placeholder="Resident name"><button class="btn" id="addResident">Add</button></div>${s.residents.map((n,i)=>`<div class="expense"><span>${n}</span><div class="actions"><button class="iconbtn" data-rename="${i}">Rename</button><button class="iconbtn" data-rm="${i}">Delete</button></div></div>`).join('')}</div>`}
function settlement(){let ts=transfers();return `<div class="hero"><h1>Settlement</h1><span class="muted">Minimized transfers for the current cycle.</span><div class="metrics"><div class="card"><span class="muted">Total</span><div class="metric">${money(total())}</div></div><div class="card"><span class="muted">Share</span><div class="metric">${money(share())}</div></div><div class="card"><span class="muted">Transfers</span><div class="metric">${ts.length}</div></div></div></div><div class="section card"><h2>Suggested payments</h2>${ts.length?ts.map(t=>`<div class="expense"><span>${t.from} → ${t.to}</span><b>${money(t.amount)}</b></div>`).join(''):`<div class="empty">Everyone is already balanced.</div>`}<button class="btn" id="settle" ${!s.expenses.length?'disabled':''}>Settle & start new cycle</button></div>`}
function history(){return `<div class="card"><h2>History</h2>${s.history.length?s.history.slice().reverse().map(h=>`<div class="expense"><div><b>${h.date}</b><div class="muted">${h.count} bills • ${h.residents} residents</div></div><b>${money(h.total)}</b></div>`).join(''):`<div class="empty">No settled cycles yet.</div>`}</div>`}
function settings(){return `<div class="card"><h2>Settings</h2><div class="form"><label class="muted">Currency<select id="currency" class="input"><option ${s.settings.currency==='USD'?'selected':''}>USD</option><option ${s.settings.currency==='EGP'?'selected':''}>EGP</option></select></label><label class="muted">Settlement day<input id="settlementDay" class="input" type="number" min="1" max="31" value="${s.settings.settlementDay}"></label><button class="btn" id="saveSettings">Save settings</button><button class="btn danger" id="clear">Delete ALL local data</button></div></div>`}
function bind(){
let a=document.getElementById('add');if(a)a.onclick=()=>{let payer=document.getElementById('payer').value,amount=Number(document.getElementById('amount').value);if(!payer||amount<=0)return toast('Select the payer and enter a valid amount.');s.expenses.push({id:Date.now(),payer,amount,date:document.getElementById('date').value,description:document.getElementById('desc').value,category:document.getElementById('cat').value});save();render();toast('Expense added')};
let ar=document.getElementById('addResident');if(ar)ar.onclick=()=>{let n=document.getElementById('newResident').value.trim();if(!n||s.residents.includes(n))return;if(n){s.residents.push(n);save();render()}};
document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this expense?')){s.expenses=s.expenses.filter(e=>e.id!=b.dataset.del);save();render()}});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let e=s.expenses.find(x=>x.id==b.dataset.edit),a=prompt('Amount',e.amount),d=prompt('Description',e.description);if(a!==null&&Number(a)>0){e.amount=Number(a);if(d!==null)e.description=d;save();render()}});
document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{let i=+b.dataset.rename,n=prompt('New name',s.residents[i]);if(n&&n.trim()){let old=s.residents[i];s.residents[i]=n.trim();s.expenses.forEach(e=>{if(e.payer===old)e.payer=n.trim()});save();render()}});
document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{let i=+b.dataset.rm,n=s.residents[i];if(s.expenses.some(e=>e.payer===n))return toast('Cannot delete a resident with expenses.');if(s.residents.length<=1)return;s.residents.splice(i,1);save();render()});
let st=document.getElementById('settle');if(st)st.onclick=()=>{if(!s.expenses.length)return;let ts=transfers();s.history.push({date:new Date().toISOString().slice(0,10),total:total(),count:s.expenses.length,residents:s.residents.length,transfers:ts});s.expenses=[];save();render();toast('Cycle settled successfully')};
let ss=document.getElementById('saveSettings');if(ss)ss.onclick=()=>{s.settings.currency=document.getElementById('currency').value;s.settings.settlementDay=Math.max(1,Math.min(31,+document.getElementById('settlementDay').value||1));save();render();toast('Settings saved')};
let cl=document.getElementById('clear');if(cl)cl.onclick=()=>{if(confirm('Delete ALL HomeShare data from this device?')){localStorage.removeItem(KEY);location.reload()}};
}
render();